---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXVWd2g3SGxLMlVIMVVxMjZGSmNQV0Rld3RORE9YQ2VKWVUrWUY1T1pXb0pvClp5V3JSTTF1QXF5a2VKa0VxYXFLN0dmOWVBUXc1NFpmT0l2a05OQ1JVS29xeG0yVlpIR3RaaVNxcjUwNkVmMnEKQXZNSG5zRENIVXc0VEFZYVA2U1pOcmptT01KYTcrMG5sb2V2VktpNmpVYVZXTTJzNldXZmJSRWoyS0dPN3JoaAo1OUJoQmtOMm9WQWdwSEFFY1MrOEVJOVZiMkV5cU8wdjgzMm85M0lOS2RTZ3ozUjA0dlM4a2dUajBTdHRtcWo5ClJ4eWEzWEJkNzkxWUxFc1pGNmhXTG9pTkhSRC8rVEFSaTNSMksxNWZxL2pJSFU4Z2xqbVEvaHNWbjlsWks2MUIKakdVU2o4MGxNay93LzkraXpGYmhZTEd3aG1tVXFneWVoY0FmNEtmYmJRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRy80Ym1UYnFyTmVWd2hTZGFGa0ZvNDRyRXdVcTZFZ1QrYTdoRlhJZkpIUkVMVTNYNXlMCkpWZGVCdDRsSHdaOENvWVFob0Z4QWVVYXZ6c25hem5YbXQwYVpnUDZSeXVNZnBxRDk4TUpnam52MEtoL1ZzRHQKZkEwUXc4TjNkNEpYanlWc3FRZWp2WUIydk1CS3h1elFGSEZIcXprMERGbkxheXJTQVhvdDdUeXQ5dm05bUtXSQpDOHdVblBvUWhFTXBpMUpxMEpRME1DekhjMG85TnlJdzRHa243ckFMRU9IQ2ZOSDlTYUJYUHpIN1dYM0tEN3RKCkVxb0U0Y1RGWk02TVRlWWYxSkFWNys5RUNXL2JRYWpsaG1zSlpoNDNyMGhEdXc3TjY1dGxZKzRwZmp3SVdrREYKaFF3MTMrUlcwRHZBZkllQjhKVVBkVEpiTVVMR1VCaDRWRlE9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth



  
# firstly, you have to encode the the .csr file -> cat akshay.csr | base64 -w 0
