apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment  # Name of the Deployment
  labels:
    app: myapp            # Label to identify the application
    type: front-end        # Label indicating the type of the application
spec:
  replicas: 3             # Number of replicas (Pods) to create
  selector:
    matchLabels:          # Criteria to match Pods for this Deployment
      type: front-end
  strategy:
    type: Recreate        # advanced approach, creates a new pod and after which to attach the volume on it.
  template:               
    metadata:
      labels:
        app: myapp        # Ensure the Pods have the same labels as the selector
        type: front-end
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:8.3.3
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
        ports:
        - containerPort: 3000
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: rest-api-data # this is for the other file
        
