apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment  # Name of the Deployment
  labels:
    app: myapp            # Label to identify the application
    type: front-end        # Label indicating the type of the application
spec:
  replicas: 3             # Number of replicas (Pods) to create
  selector:
    matchLabels:          # Criteria to match Pods for this Deployment
      type: front-end
  template:               # Template for creating the Pods
    metadata:
      labels:
        app: myapp        # Ensure the Pods have the same labels as the selector
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx       # Docker image for the container
